-- initdb/050-analytics-schema.sql
-- Comprehensive Analytics Schema for Chain Data Indexer

-- [DELETED] SWAP VOLUME HOURLY
-- [DELETED] TRANSFER VOLUME DAILY
-- [DELETED] ACTIVE WALLETS DAILY

-- [DELETED] TOKEN HOLDER COUNTS

-- [DELETED] GAS STATS DAILY
-- [DELETED] MESSAGE TYPE STATS DAILY

