-- initdb/072-reconcile-state.sql
-- Deprecated: no-op.
-- Reconciliation state is now handled by scheduler flow (initial full pass + periodic negative-only)
-- and no longer requires a dedicated table.
